---
- hosts: all
  tasks:
   - name: Update all packages
     dnf: name=* state=latest
     become: true

   - name: Install Vim
     dnf: name=vim state=latest
     become: true

   - name: Install OpenJDK (1.8)
     dnf: name=java state=latest
     become: true

   - name: Install Maven
     dnf: name=maven state=latest
     become: true

   - name: Install Git
     dnf: name=git state=latest
     become: true

   # AEM fails without this
   - name: Set open file limit for vagrant users
     pam_limits: domain=vagrant limit_type=hard limit_item=nofile value=64000
     become: true

   - name: Install AEM if not exists
     command: java -jar aem-author-4502.jar -unpack -b "../aem"
     args:
        chdir: /home/vagrant/aem_install_files/
        creates: /home/vagrant/aem/crx-quickstart
     become: false

   - name: Copy the license.properties file
     command: cp license.properties ../aem/
     args:
        chdir: /home/vagrant/aem_install_files/
        creates: /home/vagrant/aem/license.properties
     become: false

   - name: Make install directory
     command: mkdir -p /home/vagrant/aem/crx-quickstart/install 
     args:
        creates: /home/vagrant/aem/crx-quickstart/install
     become: false

#   - name: Copy all the packages that will be installed in aem
#     shell: cp ${HOME}/aem_install_files/packages_to_install/*.zip ${HOME}/aem/crx-quickstart/install/

   - name: Install systemctl entry for AEM
     copy: src="resources/aem.service" dest="/usr/lib/systemd/system/aem.service"
     become: true

   - name: Start the systemctl AEM deamon from the previous step
     service: name="aem" state=started
     become: true

   - name: Waiting for the port to be bound
     wait_for: port=4502 

   - name: Wait for the server to come up
     shell: 'curl 127.0.0.1:4502 -L -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0"'
     register: result
     until: result.stdout.find("Sign In") != -1
     retries: 60
     become: false

   - name: Check if AEM Service Pack 1 has been installed
     command: curl --fail -u admin:admin http://localhost:4502/crx/packmgr/service.jsp?cmd=ls
     register: installedBundlesPreSP1Check

   - name: Install and Activate AEM Service Pack 1 package (automatically restarts the server) if not installed
     command: curl --fail -u admin:admin -F file=@"/home/vagrant/aem_install_files/packages_to_install/servicepacks/aem-service-pkg-wrapper-6.1.SP1.zip" -F force=true -F install=true localhost:4502/crx/packmgr/service.jsp
     when: installedBundlesPreSP1Check.stdout.find("aem-service-pkg-wrapper-6.1.SP1.zip") == -1

   - name: Wait for the server to come up
     shell: 'curl 127.0.0.1:4502 -L -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0"'
     register: afterServicePackInstall
     until: afterServicePackInstall.stdout.find("Sign In") != -1
     retries: 60
     become: false

   - name: Check if ACS-Commons Library has been installed
     command: curl --fail -u admin:admin http://localhost:4502/crx/packmgr/service.jsp?cmd=ls
     register: installedBundlesPreACSCommonsCheck
   
   - name: Install ACS-Commons Library (automatically restarts the server) if not installed
     shell: 'curl --fail -u admin:admin -F file=@"/home/vagrant/aem_install_files/packages_to_install/servicepacks/acs-aem-commons-content-2.4.2-min.zip" -F force=true -F install=true localhost:4502/crx/packmgr/service.jsp && sleep 5'
     when: installedBundlesPreACSCommonsCheck.stdout.find("acs-aem-commons-content-2.4.2.zip") == -1

   - name: Wait for the server to come up
     shell: 'curl 127.0.0.1:4502 -L -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0"'
     register: afterACSCommonsInstall
     until: afterACSCommonsInstall.stdout.find("Sign In") != -1
     retries: 60
     become: false

   - name: Check if UI-apps has been installed
     command: curl --fail -u admin:admin http://localhost:4502/crx/packmgr/service.jsp?cmd=ls
     register: installedBundlesPreUIAppsCheck

   - name: Install ui-apps (components) if not installed
     shell: curl --fail -u admin:admin -F file=@"/home/vagrant/aem_install_files/packages_to_install/servicepacks/gc-aem.ui.apps-1.12.1.zip" -F force=true -F install=true localhost:4502/crx/packmgr/service.jsp 
     when: installedBundlesPreUIAppsCheck.stdout.find("gc-aem.ui.apps-1.12.1.zip") == -1
   
   - name: Get list of content packs to install
     shell: ls /home/vagrant/aem_install_files/packages_to_install/content/*
     register: packages_list

   - name: Install all content packs
     shell: 'if [[ $(curl --fail -u admin:admin http://localhost:4502/crx/packmgr/service.jsp?cmd=ls) != *$(basename "{{item}}")* ]]; then curl --fail -u admin:admin -F file=@"{{item}}" -F force=true -F install=true localhost:4502/crx/packmgr/service.jsp && sleep 2; fi'
     with_items: packages_list.stdout_lines
     become: false
     

