---
- hosts: all
  tasks:
   - name: Update all packages
     dnf: name=* state=latest
     become: true

   - name: Install Vim
     dnf: name=vim state=latest
     become: true

   - name: Install OpenJDK (1.8)
     dnf: name=java state=latest
     become: true

   - name: Install Maven
     dnf: name=maven state=latest
     become: true

   - name: Install Git
     dnf: name=git state=latest
     become: true

   # AEM fails without this
   - name: Set open file limit for vagrant users
     pam_limits: domain=vagrant limit_type=hard limit_item=nofile value=64000
     become: true

   - name: Install AEM if not exists
     command: java -jar aem-author-4502.jar -unpack -b "../aem"
     args:
        chdir: /home/vagrant/aem_install_files/
        creates: /home/vagrant/aem/crx-quickstart
     become: false

   - name: Copy the license.properties file
     command: cp license.properties ../aem/
     args:
        chdir: /home/vagrant/aem_install_files/
        creates: /home/vagrant/aem/license.properties
     become: false

   - name: Make install directory
     command: mkdir -p /home/vagrant/aem/crx-quickstart/install 
     args:
        creates: /home/vagrant/aem/crx-quickstart/install
     become: false

   - name: Install systemctl entry for AEM
     copy: src="aem_install_files/resources/aem.service" dest="/usr/lib/systemd/system/aem.service"
     become: true

   - name: Start the systemctl AEM deamon from the previous step
     service: name="aem" state=started
     become: true

   - name: Waiting for the port to be bound
     wait_for: port=4502 

   - name: Wait for the server to come up
     shell: 'curl 127.0.0.1:4502 -L -s -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0"'
     register: result
     until: result.stdout.find("Sign In") != -1
     retries: 60

   - name: Install/Activate AEM SP 1 if not installed (Restarts server on install)
     command: resources/install_aem_package.sh -f packages_to_install/servicepacks/aem-service-pkg-wrapper-6.1.SP1.zip -u 127.0.0.1:4502
     args:
        chdir: /home/vagrant/aem_install_files/
     register: sp1_install_check
     changed_when: sp1_install_check.stdout.find("Package already installed") == -1

   - name: Wait for the server to come up
     shell: 'curl 127.0.0.1:4502 -L -s -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0"'
     register: afterServicePackInstall
     until: afterServicePackInstall.stdout.find("Sign In") != -1
     retries: 60

   - name: Install/Activate ACS-Commons if not installed (Restarts server on install)
     command: resources/install_aem_package.sh -f packages_to_install/servicepacks/acs-aem-commons-content-2.4.2-min.zip -u 127.0.0.1:4502
     args:
        chdir: /home/vagrant/aem_install_files/
     register: acs_commons_check
     changed_when: acs_commons_check.stdout.find("Package already installed") == -1

   - name: Wait for the server to come up
     shell: 'curl 127.0.0.1:4502 -L -s -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0"'
     register: afterACSCommonsInstall
     until: afterACSCommonsInstall.stdout.find("Sign In") != -1
     retries: 60

   - name: Install ui-apps (components) if not installed
     command: resources/install_aem_package.sh -f packages_to_install/servicepacks/gc-aem.ui.apps-1.12.1.zip -u 127.0.0.1:4502
     args:
        chdir: /home/vagrant/aem_install_files/
     register: ui_apps_check
     changed_when: ui_apps_check.stdout.find("Package already installed") == -1
   
   - name: Get list of content packs to install
     shell: ls /home/vagrant/aem_install_files/packages_to_install/content/*
     register: packages_list

   - name: Install all content packs
     shell: 'if [[ $(curl --fail -u admin:admin http://localhost:4502/crx/packmgr/service.jsp?cmd=ls) != *$(basename "{{item}}")* ]]; then curl --fail -u admin:admin -F file=@"{{item}}" -F force=true -F install=true localhost:4502/crx/packmgr/service.jsp && sleep 2; fi'
     with_items: packages_list.stdout_lines
     

